### ISSUE TITLE
H/W buttons

### ISSUE THREAD

**Issue by acolwill** [pilnikov/KaRadio32_fork#2]
Instead of using a rotary encoder, would it be possible to use the buttons on the front of the unit to change volume or station?

**Comment by pilnikov** [comment]
try replace define PIN_ENC_BTN GPIO_NUM_15	// SW in gpio.h on GPIO_NUM_37 (38,39), 
just use the other esp32 on breadboard (not with ttgo) with the connected buttons. the result may be a surprise to you.

**Comment by pilnikov** [comment]
Now work!
